import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import { approveRefund, completeCODRefund, deleteAdminRefund, getAdminRefunds, rejectRefund } from "../../api/refundApi";

const money = value => `₹${Number(value || 0).toFixed(2)}`;
const msg = error => error.response?.data?.message || "Unable to complete this action.";
function BankDetails({ bank }) { return <div className="mt-3 rounded-xl border border-blue-200 bg-blue-50 p-3 text-sm"><b>Customer bank details</b><p className="mt-1">Account holder: {bank?.accountHolderName || "-"}<br />Account number: {bank?.accountNumber || "-"}<br />IFSC: {bank?.ifscCode || "-"}<br />Bank: {bank?.bankName || "-"}<br />Account type: {bank?.accountType || "-"}</p></div>; }
function RefundFoodImages({ items = [] }) { if (!Array.isArray(items) || !items.length) return null; return <div className="mt-3 flex flex-wrap gap-2">{items.map((item, index) => <div key={`${item.food || item.name}-${index}`} title={`${item.name || "Food"} × ${item.quantity || 1}`} className="flex items-center gap-2 rounded-lg bg-slate-50 py-1 pr-2"><img src={item.image || "https://placehold.co/48x48?text=Food"} alt={item.name || "Food"} className="h-10 w-10 rounded-md object-cover" /><span className="max-w-32 truncate text-xs font-bold">{item.name || "Food"} × {item.quantity || 1}</span></div>)}</div>; }

function AdminRefunds() {
    const [refunds, setRefunds] = useState([]), [loading, setLoading] = useState(true), [action, setAction] = useState(null), [value, setValue] = useState(""), [working, setWorking] = useState("");
    const load = async () => { setLoading(true); try { const data = await getAdminRefunds({ page: 1, limit: 50 }); setRefunds(data?.refunds || []); } catch (error) { toast.error(msg(error)); } finally { setLoading(false); } };
    useEffect(() => { load(); }, []);
    const submit = async event => { event.preventDefault(); const { refund, type } = action; if (type !== "approve" && !value.trim()) return toast.error("This field is required."); setWorking(refund._id); try { if (type === "approve") await approveRefund(refund._id, refund.requestedAmount); if (type === "reject") await rejectRefund(refund._id, value); if (type === "complete") await completeCODRefund(refund._id, value); toast.success("Refund updated."); setAction(null); await load(); } catch (error) { toast.error(msg(error)); } finally { setWorking(""); } };
    const remove = async id => { if (!window.confirm("Delete this completed refund request?")) return; setWorking(id); try { await deleteAdminRefund(id); toast.success("Refund request deleted."); await load(); } catch (error) { toast.error(msg(error)); } finally { setWorking(""); } };
    return <main className="min-h-screen bg-slate-100 p-4 md:p-8"><div className="mx-auto max-w-6xl"><h1 className="text-3xl font-black">Refund Management</h1><p className="mt-2 text-slate-600">Refunds are only for cancelled orders and always use the final order total.</p>{action ? <form onSubmit={submit} className="mt-5 rounded-2xl bg-amber-50 p-4"><b>{action.type} · {action.refund.order?.orderNumber}</b>{action.type === "approve" ? <p className="mt-3 font-bold">Final refund amount: {money(action.refund.requestedAmount)}</p> : <label className="mt-3 grid gap-1 text-sm font-bold">{action.type === "complete" ? "Bank transfer reference" : "Rejection note"}<textarea value={value} onChange={e => setValue(e.target.value)} className="rounded-lg border p-2" /></label>}<button disabled={working === action.refund._id} className="mt-3 rounded-lg bg-slate-900 px-4 py-2 font-bold text-white">Confirm</button><button type="button" onClick={() => setAction(null)} className="ml-2 rounded-lg border px-4 py-2 font-bold">Cancel</button></form> : null}<div className="mt-6 space-y-4">{loading ? <p>Loading refunds...</p> : refunds.map(refund => <article key={refund._id} className="rounded-2xl bg-white p-5"><b>{refund.order?.orderNumber || "Order"} · {refund.status}</b><p className="mt-1 text-sm">Payment: {refund.order?.paymentMethod || refund.refundType} · Final refund: {money(refund.requestedAmount)} · Approved: {money(refund.approvedAmount)}</p><RefundFoodImages items={refund.order?.items} /><BankDetails bank={refund.order?.refundBankDetails || refund.bankDetails} /><p className="mt-3 text-sm"><b>Refund reason:</b> {refund.reason}</p>{["REQUESTED", "UNDER_REVIEW"].includes(refund.status) ? <div className="mt-3 flex gap-3"><button type="button" onClick={() => { setAction({ refund, type: "approve" }); setValue(""); }} className="font-bold text-green-700">Approve full refund</button><button type="button" onClick={() => { setAction({ refund, type: "reject" }); setValue(""); }} className="font-bold text-red-600">Reject</button></div> : refund.status === "APPROVED" && refund.refundType === "COD" ? <button type="button" onClick={() => { setAction({ refund, type: "complete" }); setValue(""); }} className="mt-3 font-bold">Complete bank transfer</button> : ["COMPLETED", "REJECTED"].includes(refund.status) ? <button disabled={working === refund._id} type="button" onClick={() => remove(refund._id)} className="mt-3 font-bold text-red-600">Delete request</button> : null}</article>)}</div></div></main>;
}

export default AdminRefunds;
