import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import { getMyOrders } from "../../api/orderApi";
import { createRefundRequest, deleteMyRefund, getMyRefunds } from "../../api/refundApi";

const money = value => `₹${Number(value || 0).toFixed(2)}`;
const msg = error => error.response?.data?.message || "Unable to complete this action.";
const FoodItems = ({ items = [] }) => <div className="mt-3 grid gap-2 sm:grid-cols-2">{items.map((item, index) => <div key={`${item.food}-${index}`} className="flex items-center gap-3 rounded-xl border bg-slate-50 p-2"><img src={item.image || "https://placehold.co/80x80?text=Food"} alt={item.name} className="h-14 w-14 rounded-lg object-cover" /><div><b>{item.name}</b><p className="text-xs text-slate-500">Qty: {item.quantity} · {money(item.unitPrice)} each</p><p className="text-sm font-bold">{money(item.subtotal)}</p></div></div>)}</div>;
const BankDetails = ({ bank }) => <div className="mt-3 rounded-xl border border-blue-200 bg-blue-50 p-3 text-sm"><b>COD refund bank details</b><p className="mt-1">Account holder: {bank?.accountHolderName || "-"}<br />Account number: {bank?.accountNumber || "-"}<br />IFSC: {bank?.ifscCode || "-"}<br />Bank: {bank?.bankName || "-"}<br />Account type: {bank?.accountType || "-"}</p></div>;

function Refunds() {
    const [orders, setOrders] = useState([]);
    const [refunds, setRefunds] = useState([]);
    const [selected, setSelected] = useState(null);
    const [reason, setReason] = useState("");
    const [bank, setBank] = useState({ accountHolderName: "", accountNumber: "", ifscCode: "", bankName: "", accountType: "SAVINGS" });
    const [working, setWorking] = useState("");
    const load = async () => { try { const [orderData, refundData] = await Promise.all([getMyOrders(), getMyRefunds()]); setOrders(orderData || []); setRefunds(refundData || []); } catch (error) { toast.error(msg(error)); } };
    useEffect(() => { load(); }, []);
    const active = refunds.filter(refund => ["REQUESTED", "UNDER_REVIEW", "APPROVED", "PROCESSING"].includes(refund.status)).map(refund => String(refund.order?._id || refund.order));
    const submit = async event => { event.preventDefault(); if (!reason.trim()) return toast.error("Enter refund reason."); if (selected.paymentMethod === "COD" && Object.values(bank).some(value => !String(value).trim())) return toast.error("Fill all COD bank details."); setWorking(selected._id); try { await createRefundRequest({ orderId: selected._id, reason, bankDetails: selected.paymentMethod === "COD" ? bank : undefined }); toast.success("Refund request submitted."); setSelected(null); setReason(""); load(); } catch (error) { toast.error(msg(error)); } finally { setWorking(""); } };
    const remove = async id => { if (!window.confirm("Delete this completed refund request?")) return; setWorking(id); try { await deleteMyRefund(id); setRefunds(current => current.filter(refund => String(refund._id) !== String(id))); toast.success("Refund request deleted."); } catch (error) { toast.error(msg(error)); } finally { setWorking(""); } };
    const eligible = orders.filter(order => ["DELIVERED", "CANCELLED"].includes(order.status) && (order.paymentMethod === "COD" || order.paymentStatus === "SUCCESS"));
    const field = (key, label) => <label className="grid gap-1 text-sm font-bold">{label}<input required value={bank[key]} onChange={event => setBank({ ...bank, [key]: event.target.value })} className="rounded-xl border bg-white p-2 font-normal" /></label>;
    return <main className="min-h-screen bg-slate-50 p-4 md:p-8"><div className="mx-auto max-w-5xl"><h1 className="text-3xl font-black">Refunds</h1><section className="mt-6 space-y-3">{eligible.map(order => <article key={order._id} className="rounded-2xl border bg-white p-4"><b>{order.orderNumber}</b><p className="text-sm">{order.paymentMethod} · {money(order.totalAmount)}</p><FoodItems items={order.items} /><button disabled={active.includes(String(order._id))} onClick={() => setSelected(order)} className="mt-3 rounded-xl bg-slate-900 px-4 py-2 font-bold text-white disabled:opacity-50">{active.includes(String(order._id)) ? "Request active" : "Request refund"}</button></article>)}</section>{selected ? <form onSubmit={submit} className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-5"><h2 className="font-black">Refund: {selected.orderNumber}</h2><FoodItems items={selected.items} /><label className="mt-3 grid gap-1 text-sm font-bold">Refund reason<textarea required value={reason} onChange={event => setReason(event.target.value)} className="min-h-24 rounded-xl border bg-white p-3 font-normal" /></label>{selected.paymentMethod === "COD" ? <div className="mt-4"><h3 className="font-black">Bank details for COD refund</h3><div className="mt-2 grid gap-3 sm:grid-cols-2">{field("accountHolderName", "Account holder name")}{field("accountNumber", "Account number")}{field("ifscCode", "IFSC code")}{field("bankName", "Bank name")}<label className="grid gap-1 text-sm font-bold">Account type<select value={bank.accountType} onChange={event => setBank({ ...bank, accountType: event.target.value })} className="rounded-xl border bg-white p-2 font-normal"><option>SAVINGS</option><option>CURRENT</option></select></label></div></div> : null}<button disabled={working} className="mt-4 rounded-xl bg-slate-900 px-4 py-2 font-bold text-white">Submit refund request</button><button type="button" onClick={() => setSelected(null)} className="ml-2 rounded-xl border px-4 py-2 font-bold">Cancel</button></form> : null}<section className="mt-8"><h2 className="text-lg font-black">My refund requests</h2>{refunds.map(refund => <article key={refund._id} className="mt-3 rounded-2xl border bg-white p-4"><b>{refund.order?.orderNumber}</b><FoodItems items={refund.order?.items} /><p className="mt-2 text-sm">Reason: {refund.reason}<br />Status: {refund.status} · Requested: {money(refund.requestedAmount)}</p>{refund.refundType === "COD" ? <BankDetails bank={refund.bankDetails} /> : null}{refund.status === "COMPLETED" ? <button disabled={working === refund._id} onClick={() => remove(refund._id)} className="mt-3 font-bold text-red-600 disabled:opacity-50">Delete request</button> : null}</article>)}</section></div></main>;
}

export default Refunds;
