import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import { getMyOrders } from "../../api/orderApi";
import { createRefundRequest, getMyRefunds } from "../../api/refundApi";

const message = (error) => error.response && error.response.data && error.response.data.message ? error.response.data.message : "Something went wrong.";
const money = (amount) => "₹" + Number(amount || 0).toFixed(2);
function Refunds() {
    const [orders, setOrders] = useState([]); const [refunds, setRefunds] = useState([]); const [loading, setLoading] = useState(true); const [working, setWorking] = useState("");
    const load = async () => { setLoading(true); try { const result = await Promise.all([getMyOrders(), getMyRefunds()]); setOrders(Array.isArray(result[0]) ? result[0] : []); setRefunds(Array.isArray(result[1]) ? result[1] : []); } catch (error) { toast.error(message(error)); } finally { setLoading(false); } };
    // eslint-disable-next-line react-hooks/set-state-in-effect
    useEffect(() => { load(); }, []);
    const request = async (order) => { const reason = window.prompt("Why do you need a refund?"); if (!reason) return; let bankDetails; if (order.paymentMethod === "COD") { const accountHolderName = window.prompt("Account holder name:"); const accountNumber = window.prompt("Account number:"); const ifscCode = window.prompt("IFSC code:"); const bankName = window.prompt("Bank name:"); const accountType = window.prompt("Account type: SAVINGS or CURRENT"); if (!accountHolderName || !accountNumber || !ifscCode || !bankName || !accountType) return; bankDetails = { accountHolderName, accountNumber, ifscCode, bankName, accountType: accountType.toUpperCase() }; } setWorking(order._id); try { await createRefundRequest({ orderId: order._id, reason, bankDetails }); toast.success("Refund request submitted."); await load(); } catch (error) { toast.error(message(error)); } finally { setWorking(""); } };
    const activeOrderIds = refunds.filter((refund) => ["REQUESTED", "UNDER_REVIEW", "APPROVED", "PROCESSING"].includes(refund.status)).map((refund) => String(refund.order && refund.order._id ? refund.order._id : refund.order));
    return <main className="min-h-screen bg-slate-50 p-4 md:p-8"><div className="mx-auto max-w-5xl"><h1 className="text-3xl font-black">Refunds</h1><p className="mt-2 text-slate-500">Refund eligibility and final amount are validated by the server.</p>{loading ? <p className="mt-6">Loading refunds...</p> : <><section className="mt-6"><h2 className="text-lg font-black">Request a refund</h2><div className="mt-3 space-y-3">{orders.filter((order) => order.status === "DELIVERED" || order.status === "CANCELLED").map((order) => <article key={order._id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border bg-white p-4"><div><p className="font-bold">{order.orderNumber}</p><p className="text-sm text-slate-500">{order.paymentMethod} · {order.paymentStatus} · {money(order.totalAmount)}</p></div><button type="button" disabled={working === order._id || activeOrderIds.includes(String(order._id))} onClick={() => request(order)} className="rounded-xl bg-slate-900 px-4 py-2 font-bold text-white disabled:opacity-50">{activeOrderIds.includes(String(order._id)) ? "Request active" : "Request refund"}</button></article>)}</div></section><section className="mt-8"><h2 className="text-lg font-black">My refund requests</h2><div className="mt-3 space-y-3">{refunds.length ? refunds.map((refund) => <article key={refund._id} className="rounded-2xl border bg-white p-4"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-bold">{refund.order && refund.order.orderNumber ? refund.order.orderNumber : "Order"}</p><p className="mt-1 text-sm text-slate-500">{refund.reason}</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{refund.status}</span></div><p className="mt-3 text-sm">Requested: {money(refund.requestedAmount)} · Approved: {money(refund.approvedAmount)}</p>{refund.failureReason ? <p className="mt-2 text-sm text-red-600">{refund.failureReason}</p> : null}{refund.bankTransferReference ? <p className="mt-2 text-sm">Transfer reference: {refund.bankTransferReference}</p> : null}</article>) : <p className="rounded-2xl bg-white p-5 text-slate-500">No refund requests yet.</p>}</div></section></>}</div></main>;
}
export default Refunds;
